// Code generated by MockGen. DO NOT EDIT.
// Source: auth_repository.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/chocoko/character-support-walk-backend/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateAuthIdentity mocks base method.
func (m *MockAuthRepository) CreateAuthIdentity(ctx context.Context, authIdentity entity.AuthIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthIdentity", ctx, authIdentity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuthIdentity indicates an expected call of CreateAuthIdentity.
func (mr *MockAuthRepositoryMockRecorder) CreateAuthIdentity(ctx, authIdentity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthIdentity", reflect.TypeOf((*MockAuthRepository)(nil).CreateAuthIdentity), ctx, authIdentity)
}

// CreateRefreshToken mocks base method.
func (m *MockAuthRepository) CreateRefreshToken(ctx context.Context, refreshToken entity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) CreateRefreshToken(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).CreateRefreshToken), ctx, refreshToken)
}

// DeleteAuthIdentitiesByUserID mocks base method.
func (m *MockAuthRepository) DeleteAuthIdentitiesByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthIdentitiesByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthIdentitiesByUserID indicates an expected call of DeleteAuthIdentitiesByUserID.
func (mr *MockAuthRepositoryMockRecorder) DeleteAuthIdentitiesByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthIdentitiesByUserID", reflect.TypeOf((*MockAuthRepository)(nil).DeleteAuthIdentitiesByUserID), ctx, userID)
}

// FindByProviderAndProviderUserID mocks base method.
func (m *MockAuthRepository) FindByProviderAndProviderUserID(ctx context.Context, provider entity.AuthProvider, providerUserID string) (*entity.AuthIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderAndProviderUserID", ctx, provider, providerUserID)
	ret0, _ := ret[0].(*entity.AuthIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderAndProviderUserID indicates an expected call of FindByProviderAndProviderUserID.
func (mr *MockAuthRepositoryMockRecorder) FindByProviderAndProviderUserID(ctx, provider, providerUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderAndProviderUserID", reflect.TypeOf((*MockAuthRepository)(nil).FindByProviderAndProviderUserID), ctx, provider, providerUserID)
}

// FindRefreshTokenByHash mocks base method.
func (m *MockAuthRepository) FindRefreshTokenByHash(ctx context.Context, tokenHash string) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRefreshTokenByHash indicates an expected call of FindRefreshTokenByHash.
func (mr *MockAuthRepositoryMockRecorder) FindRefreshTokenByHash(ctx, tokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshTokenByHash", reflect.TypeOf((*MockAuthRepository)(nil).FindRefreshTokenByHash), ctx, tokenHash)
}

// RevokeRefreshToken mocks base method.
func (m *MockAuthRepository) RevokeRefreshToken(ctx context.Context, refreshTokenID uuid.UUID, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, refreshTokenID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) RevokeRefreshToken(ctx, refreshTokenID, revokedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).RevokeRefreshToken), ctx, refreshTokenID, revokedAt)
}

// UpdateRefreshTokenRevokedAtByUserID mocks base method.
func (m *MockAuthRepository) UpdateRefreshTokenRevokedAtByUserID(ctx context.Context, userID uuid.UUID, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshTokenRevokedAtByUserID", ctx, userID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshTokenRevokedAtByUserID indicates an expected call of UpdateRefreshTokenRevokedAtByUserID.
func (mr *MockAuthRepositoryMockRecorder) UpdateRefreshTokenRevokedAtByUserID(ctx, userID, revokedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshTokenRevokedAtByUserID", reflect.TypeOf((*MockAuthRepository)(nil).UpdateRefreshTokenRevokedAtByUserID), ctx, userID, revokedAt)
}
