// Code generated by MockGen. DO NOT EDIT.
// Source: walk_option_repository.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/chocoko/character-support-walk-backend/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockWalkOptionRepository is a mock of WalkOptionRepository interface.
type MockWalkOptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalkOptionRepositoryMockRecorder
}

// MockWalkOptionRepositoryMockRecorder is the mock recorder for MockWalkOptionRepository.
type MockWalkOptionRepositoryMockRecorder struct {
	mock *MockWalkOptionRepository
}

// NewMockWalkOptionRepository creates a new mock instance.
func NewMockWalkOptionRepository(ctrl *gomock.Controller) *MockWalkOptionRepository {
	mock := &MockWalkOptionRepository{ctrl: ctrl}
	mock.recorder = &MockWalkOptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalkOptionRepository) EXPECT() *MockWalkOptionRepositoryMockRecorder {
	return m.recorder
}

// SelectOption mocks base method.
func (m *MockWalkOptionRepository) SelectOption(ctx context.Context) ([]entity.WalkOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOption", ctx)
	ret0, _ := ret[0].([]entity.WalkOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOption indicates an expected call of SelectOption.
func (mr *MockWalkOptionRepositoryMockRecorder) SelectOption(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOption", reflect.TypeOf((*MockWalkOptionRepository)(nil).SelectOption), ctx)
}
