// Code generated by MockGen. DO NOT EDIT.
// Source: id_token_validator.go

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	auth "github.com/chocoko/character-support-walk-backend/internal/domain/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockIDTokenValidator is a mock of IDTokenValidator interface.
type MockIDTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIDTokenValidatorMockRecorder
}

// MockIDTokenValidatorMockRecorder is the mock recorder for MockIDTokenValidator.
type MockIDTokenValidatorMockRecorder struct {
	mock *MockIDTokenValidator
}

// NewMockIDTokenValidator creates a new mock instance.
func NewMockIDTokenValidator(ctrl *gomock.Controller) *MockIDTokenValidator {
	mock := &MockIDTokenValidator{ctrl: ctrl}
	mock.recorder = &MockIDTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDTokenValidator) EXPECT() *MockIDTokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockIDTokenValidator) Validate(ctx context.Context, token string) (*auth.IDTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, token)
	ret0, _ := ret[0].(*auth.IDTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockIDTokenValidatorMockRecorder) Validate(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockIDTokenValidator)(nil).Validate), ctx, token)
}
