services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
    env_file:
      - .example.env
    ports:
      - "8080:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: character-support-walk-api

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .example.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 3
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports: 
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ../api/openapi.yaml:/openapi.yaml:ro
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otelcol/otel-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    depends_on:
      - prometheus
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317"

volumes:
  postgres_data: